INSERT INTO cat_state(id_state,id_country,name,abbreviation,description) VALUES 
(09,1,'Distrito Federal','Distrito Federal','Distrito Federal')
,(01,1,'Aguascalientes','Aguascalientes','Aguascalientes')
,(02,1,'Baja California','Baja California','Baja California')
,(03,1,'Baja California Sur','Baja California Sur','Baja California Sur')
,(04,1,'Campeche','Campeche','Campeche')
,(05,1,'Coahuila de Zaragoza','Coahuila de Zaragoza','Coahuila de Zaragoza')
,(06,1,'Colima','Colima','Colima')
,(07,1,'Chiapas','Chiapas','Chiapas')
,(08,1,'Chihuahua','Chihuahua','Chihuahua')
,(10,1,'Durango','Durango','Durango')
,(11,1,'Guanajuato','Guanajuato','Guanajuato')
,(12,1,'Guerrero','Guerrero','Guerrero')
,(13,1,'Hidalgo','Hidalgo','Hidalgo')
,(14,1,'Jalisco','Jalisco','Jalisco')
,(15,1,'México','México','México')
,(16,1,'Michoacán de Ocampo','Michoacán de Ocampo','Michoacán de Ocampo')
,(17,1,'Morelos','Morelos','Morelos')
,(18,1,'Nayarit','Nayarit','Nayarit')
,(19,1,'Nuevo León','Nuevo León','Nuevo León')
,(20,1,'Oaxaca','Oaxaca','Oaxaca')
,(21,1,'Puebla','Puebla','Puebla')
,(22,1,'Querétaro','Querétaro','Querétaro')
,(23,1,'Quintana Roo','Quintana Roo','Quintana Roo')
,(24,1,'San Luis Potosí','San Luis Potosí','San Luis Potosí')
,(25,1,'Sinaloa','Sinaloa','Sinaloa')
,(26,1,'Sonora','Sonora','Sonora')
,(27,1,'Tabasco','Tabasco','Tabasco')
,(28,1,'Tamaulipas','Tamaulipas','Tamaulipas')
,(29,1,'Tlaxcala','Tlaxcala','Tlaxcala')
,(30,1,'Veracruz de Ignacio de la Llave','Veracruz de Ignacio de la Llave','Veracruz de Ignacio de la Llave')
,(31,1,'Yucatán','Yucatán','Yucatán')
,(32,1,'Zacatecas','Zacatecas','Zacatecas')
,(33,1,'No proporcionado','No proporcionado','No proporcionado')
;